### ISSUE TITLE
Unable to find option to delete the report.

### ISSUE THREAD

**Issue by hemano** [email2vimalraj/docker-extentx#3]
Is there any way to deleted the past reports?
<img width="1209" alt="screen shot 2017-08-20 at 11 57 09 am" src="https://user-images.githubusercontent.com/10948392/29492572-8f37468c-859d-11e7-8c38-99187d9d7058.png">

**Comment by email2vimalraj** [comment]
An admin can delete the report. And BTW, for further help, kindly log this issue into the ExtentX repo.
